### ISSUE TITLE
Rework AST to convert strings to expressions

### ISSUE THREAD

**Issue by MovingtoMars** [yberreby/rgo#12]
Right now, in the AST, some things are stored as strings when they should be access expressions of some kind.

I noticed this comment in ast.rs: https://github.com/yberreby/rgo/blob/master/src/ast/mod.rs#L243.

The problem is that it won't work to store the function name as a string. It needs to be an expression. 90% of function calls will use a simple ident expression. See https://github.com/golang/go/blob/master/src/go/ast/ast.go#L317.

**Comment by yberreby** [comment]
The Rust struct you linked is a function _declaration_, not a function _call_, though.

Here's the relevant struct in the Go source: https://github.com/golang/go/blob/master/src/go/ast/ast.go#L923-L930

**Comment by MovingtoMars** [comment]
Ah, misread. Sorry!
