### ISSUE TITLE
Finish implementing the lexer

### ISSUE THREAD

**Issue by yberreby** [yberreby/rgo#13]
Remaining work:
- [x] rune literals
- [x] floating-point literals
- [x] imaginary literals
- [x] hexadecimal integer literals
- [x] octal integer literals
- [x] adding back unit tests - they were removed at some point because of breaking changes

**Comment by MovingtoMars** [comment]
When should strings be actually interpreted?

**Comment by MovingtoMars** [comment]
I added some tests to lexer.rs: https://github.com/yberreby/rgo/blob/master/src/lexer/mod.rs#L695

**Comment by yberreby** [comment]
I think it's better to interpret strings during parsing. [Here's the relevant section of the parser](https://github.com/yberreby/rgo/blob/cd128d8fe91c5d4daa5e3cbe5b679cedce7ae28b/src/parser/mod.rs#L597-L600).

Oh, and thank you very much for your contributions :)

**Comment by yberreby** [comment]
I fear you may have introduced an infinite loop, though, because the integration tests are hanging indefinitely since your change.

**Comment by MovingtoMars** [comment]
Oh, I found the problem!

**Comment by yberreby** [comment]
I think it might be a good idea to use GitHub PRs instead of pushing directly to master for non-trivial changes, so that this kind of change stands out and can be discussed in the GitHub UI.

**Comment by MovingtoMars** [comment]
Yup, I will next time.

**Comment by MovingtoMars** [comment]
So what needs to be done for interpreted strings in the lexer?

**Comment by yberreby** [comment]
Well... nothing at all, it seems. It's in the parser that they must be interpreted so my checklist item was wrong.

**Comment by MovingtoMars** [comment]
Didn't you just say that should be done in the parser?

**Comment by yberreby** [comment]
Yes I did, I accidentally hit "comment" before realizing that belonged to the parser. Reload to see my edit, and sorry.
